"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getStorage = exports.createFakeStorage = exports.S3StorageAdapter = exports.LocalStorageAdapter = exports.StorageError = void 0;
var types_1 = require("./types");
Object.defineProperty(exports, "StorageError", { enumerable: true, get: function () { return types_1.StorageError; } });
var local_1 = require("./local");
Object.defineProperty(exports, "LocalStorageAdapter", { enumerable: true, get: function () { return local_1.LocalStorageAdapter; } });
var s3_1 = require("./s3");
Object.defineProperty(exports, "S3StorageAdapter", { enumerable: true, get: function () { return s3_1.S3StorageAdapter; } });
var fake_1 = require("./fake");
Object.defineProperty(exports, "createFakeStorage", { enumerable: true, get: function () { return fake_1.createFakeStorage; } });
var factory_1 = require("./factory");
Object.defineProperty(exports, "getStorage", { enumerable: true, get: function () { return factory_1.getStorage; } });
